### PR TITLE
Update serverlist.json

### PR DESCRIPTION
**Pull request by donghyunyoo**
Hi all, 
We would like to release AGH map.

### CODE REVIEW

**Comment by kentarou-fukuda** [comment]
Hi,

Would you please use one of two procedures to contribute to HULOP project?

https://github.com/hulop/00Readme

If it is an one-time contribution, you may simply use B: DCO procedure.

Thanks!

**Comment by donghyunyoo** [comment]
Hi, 

I followed the following procedure. but it didn't work. 
when I push to the branch, it said "Permission to hulop/hulop.github.io.git denied"

Clone HULOP repogitory
Create your feature branch (git checkout -b my-new-feature)
Commit your changes (git commit -s -am 'Add some feature')
Push to the branch (git push origin my-new-feature)
Create a new Pull Request

**Comment by daisukes** [comment]
Hi @donghyunyoo ,
Sorry for the inconvenience about updating the server list.
I thought you are in the member of HULOP. Please send [CLA](https://github.com/hulop/00Readme#a-contributor-license-agreement-cla) to @kentarou-fukuda to join the team! 

@kentarou-fukuda 
I think we need to update the [procedure](https://github.com/hulop/00Readme#procedure) for one-time contribution from non-members. They may need a forked repo but I'm not sure the sign-off method works with the forked repo.

**Comment by kentarou-fukuda** [comment]
Hi @donghyunyoo,
Excuse me for bothering you... Would you please send CLA to socacc@jp.ibm.com?
We will update the DCO procedure later.

**Comment by kentarou-fukuda** [comment]
Hi all,

The update is already merged in the repo ( b143ada69d6f2f27639e00eb028867b8536c088e ).
So, I'll close this request, and will update the procedure later.

Thanks.

**Pull request closed without merging**
